services:
  typst-runner:
    image: typst-runner:latest
    container_name: typst-runner
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RUNNER_MANAGER_TOKEN=
      - RUNNER_NAME=typst-runner
      - REPO_OWNER=Toniolo-Marco
      - REPO_NAME=git-for-dummies
